def genAssFile(segemnts, target_file):

    ass_header = """[Script Info]
; Script generated by aatsg
; https://github.com/zyzsdy/aatsg
Original Script: aatsg
ScriptType: v4.00+
PlayDepth: 0
Timer: 100.0000
WrapStyle: 0
ScaledBorderAndShadow: no
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Orig,思源黑体 Light,60,&H0084E5F7,&H000000FF,&H000C4D4E,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,45,1
Style: Target,思源黑体 Normal,70,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,45,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    
    ass_lines = []
    for seg in segemnts:
        ass_lines.append(f"Dialogue: 0,{timeFormat(seg.start)},{timeFormat(seg.end)},Orig,SPEAKER_00,0,0,0,,{seg.text}")

    ass_file = ass_header + '\n'.join(ass_lines)

    with open(target_file, 'w', encoding='utf-8') as file:
        file.write(ass_file)

def timeFormat(time):
    hours = int(time // 3600)
    minutes = int((time % 3600) // 60)
    seconds = time % 60
    return f"{hours:02d}:{minutes:02d}:{seconds:05.2f}"