import sys
import re
import openaiconfig
import requests
import json
import yaml
from itertools import zip_longest

def parse_ass_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    
    events_section = False
    dialogues = []

    for line in lines:
        if "[Events]" in line:
            events_section = True
            continue
        if events_section:
            if line.startswith("Dialogue:"):
                linepart = line[10:].strip()
                parts = line.split(',')
                start = parts[1]
                end = parts[2]
                text = parts[-1]
                dialogues.append({
                    'start': start,
                    'end': end,
                    'text': text.strip()
                })

    if not events_section:
        print("Error: ASS解析失败：你的字幕里至少得有[Events]吧。")
        sys.exit(1)

    return dialogues

def send_trans_api(transbag):
    orig_yaml = [{'id': i + 1, 'text': t['text']} for i, t in enumerate(transbag)]
    orig_yaml_string = yaml.dump(orig_yaml, allow_unicode=True, default_style=None, default_flow_style=False)

    conf = openaiconfig.OpenAIConfig()

    user_prompt = conf.multiple_prompt
    user_prompt = user_prompt.replace("{{yaml}}", orig_yaml_string)
    user_prompt = user_prompt.replace("{{user_dict}}", conf.user_dict)


    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {conf.api_key}"
    }
    data = {
        "model": conf.model_name,
        "temperature": 0,
        "messages": [
            {
                "role": "system",
                "content": f"{conf.system_prompt}"
            },
            {
                "role": "user",
                "content": f"{user_prompt}"
            }
        ]
    }

    for i in range(3):
        succ = False
        try:
            response = requests.post(conf.url, headers=headers, data=json.dumps(data, ensure_ascii=False).encode('utf-8'))
            response_json = response.json()
    
            translated_content = response_json['choices'][0]['message']['content']
        except Exception as e:
            print(f"Error: 翻译API请求失败：{e}")
            continue

        try:
            translated_content = re.sub(r'(?<=:)(\S)', r' \1', translated_content) # 大模型返回的结果有时候冒号后面没有空格，给他补上
            translated_list = yaml.load(translated_content, Loader=yaml.FullLoader)
            succ = True
        except Exception as e:
            print(f"Error: 翻译结果解析失败：{e}")
            print(translated_content)
            continue

        break

    if succ:
        for t in translated_list:
            index = t['id'] - 1
            transbag[index]['translated'] = t['text']

    return transbag


def translate_ass(dialogues):
    translated = []

    bag = []
    total_len = len(dialogues)
    for i, dialogue in enumerate(dialogues):
        bag.append(dialogue)

        if len(bag) == 3:
            print(f"正在发送翻译请求：Line {i} / {total_len}")
            trans_result = send_trans_api(bag)
            translated.extend(trans_result)
            bag = []
        
    if len(bag) > 0:
        trans_result = send_trans_api(bag)

    return translated

def gen_ass(trans, target_file):

    ass_header = """[Script Info]
; Script generated by aatsg
; https://github.com/zyzsdy/aatsg
Original Script: aatsg
ScriptType: v4.00+
PlayDepth: 0
Timer: 100.0000
WrapStyle: 0
ScaledBorderAndShadow: no
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Orig,思源黑体 Light,60,&H0084E5F7,&H000000FF,&H000C4D4E,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,45,1
Style: Target,思源黑体 Normal,70,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,45,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    
    ass_lines = []
    for text in trans:
        start = text['start']
        end = text['end']
        orig = text['text']
        tran = ""
        if 'translated' in text:
            tran = text['translated']
        ass_lines.append(f"Dialogue: 0,{start},{end},Orig,SPEAKER_00,0,0,0,,{orig}")
        ass_lines.append(f"Dialogue: 0,{start},{end},Target,SPEAKER_00,0,0,0,,{tran}")

    ass_file = ass_header + '\n'.join(ass_lines)

    with open(target_file, 'w', encoding='utf-8') as file:
        file.write(ass_file)

        

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python asstrans.py <path_to_ass_file>")
        sys.exit(1)
    
    ass_file_path = sys.argv[1]
    target_file_path = ass_file_path.replace('.ass', '_translated.ass')

    dialogues = parse_ass_file(ass_file_path)
    translated_result = translate_ass(dialogues)
    gen_ass(translated_result, target_file_path)

    print("ASS文件已经生成在：" + target_file_path)
    